### ISSUE TITLE
"Error: Internal Error in Spin at ../src/Linux/LinuxInterface.cpp(54)"

### ISSUE THREAD

**Issue by stonewatered** [chrishamm/DuetSoftwareFramework#114] opened 2020-04-14 16:52 UTC
Issue appeared with RC6 (I didn't test RC5 but I didn't get the problem with RC4.

I have tested using a number of previously successful prints - the failure occurs after a few minutes of printing (but each time at a different section of gcode).

**Comment by chrishamm** [comment] 2020-04-14 17:32
Are you using RC7 and the latest unstable DSF 1.3.2?

**Comment by chrishamm** [comment] 2020-04-24 16:34
Cannot reproduce this, closing.

**Closed by chrishamm** 2020-04-24 16:34 UTC
