### ISSUE TITLE
DCS: Heater.Sensor is hard coded to heater index

### ISSUE THREAD

**Issue by gtjoseph** [chrishamm/DuetSoftwareFramework#67] opened 2019-10-11 21:20 UTC
It looks like the DCS hard codes the "sensor" entry in "heaters" to be the same index as the heater so the model shows incorrect sensor number if it's not the same as the heater.

**Comment by chrishamm** [comment] 2019-10-17 16:11
Essentially a duplicate of #69

**Closed by chrishamm** 2019-10-17 16:11 UTC
